# Generated by Django 6.0 on 2025-12-29 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product searched', max_length=255)),
                ('best_price', models.DecimalField(decimal_places=2, help_text='Best price found for the product', max_digits=10)),
                ('store', models.CharField(help_text='Store where best price was found', max_length=100)),
                ('searched_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the search was performed')),
                ('user', models.ForeignKey(help_text='User who performed the search', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', '-searched_at'], name='api_searchh_user_id_e70227_idx'), models.Index(fields=['user'], name='api_searchh_user_id_34f1fd_idx')],
            },
        ),
    ]
