# Generated by Django 6.0 on 2025-12-25 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, help_text='User email address (used for login)', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text='User first name', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='User last name', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when user registered')),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='users_custo_email_c80f75_idx'), models.Index(fields=['-date_joined'], name='users_custo_date_jo_ecd7c8_idx')],
            },
        ),
    ]
