# Generated by Django 6.0 on 2025-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Address line 1 (House/Flat No., Building Name)', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Address line 2 (Street, Area, Landmark)', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='India', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, help_text='Pincode', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100),
        ),
    ]
